ignored = [
    "sigs.k8s.io/controller-tools/testData/*",  # it's just testdata
]

[[constraint]]
  name="k8s.io/api"
  version="kubernetes-1.14.1"

[[constraint]]
  name="k8s.io/apiextensions-apiserver"
  version="kubernetes-1.14.1"

[[constraint]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.14.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"
 
[[constraint]]
  name = "sigs.k8s.io/yaml"
  version = "v1.1.0"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[prune]
  go-tests = true
  unused-packages = true
